restricted-worlds:
  - world
  - custom_world

prevent-rotation: true
prevent-placing-items: true
prevent-knocking-by-player: true
prevent-knocking-by-entity: true
prevent-placing-frames: true

messages:
  rotation: "§cYou cannot rotate item frames in this world!"
  placing-items: "§cYou cannot place items into item frames here!"
  knocking-by-player: "§cYou cannot break item frames here!"
  knocking-by-entity: "§cEntities cannot destroy item frames here!"
  placing-frames: "§cYou cannot place item frames in this world!"
